### ISSUE TITLE
Add upper bound to `errors` dependency

### ISSUE THREAD

**Issue by Gabriel439** [myfreeweb/http-link-header#1]
`errors-2.0` will switch to use `ExceptT` instead of `EitherT`.  If that will break your package then add an upper bound of `errors < 2.0` to your dependencies.

**Comment by myfreeweb** [comment]
I only use `hush` in this package so... it probably won't break anything?

**Comment by Gabriel439** [comment]
That's right.  You're `errors-2.0` compatible if you only use `hush`.  I'll go ahead and close this issue.  Thanks for checking! :)
