### ISSUE TITLE
Imports are brittle

### ISSUE THREAD

**Issue by sjshuck** [myfreeweb/http-link-header#12]
The goal of #10 was to allow the `Link` type to contain any representation of a URI, so as not to force conversions to/from `Network.URI.URI` at runtime even when unnecessary (e.g., if the user only cares about printing `Text` or is using some alternate URL-modeling library).

For backwards compatibility, we introduced the `IsURI` typeclass with `Text` and `URI` instances and new parser functions that emit `(IsURI uri) => [GLink uri]`, redefining `Link` as a `GLink Network.URI.URI` type synonym, keeping all the existing functions restricted to that type so they would work the same way, and adding new polymorphic functions with slightly different names.  Certain design sacrifices were made (`GLink` the type has a different name than `Link` the constructor) to facilitate this backwards-compatible change.

However, it's not actually backwards compatible.  `Link` is now a type alias, so very reasonable imports like
```haskell
import Network.HTTP.Link.Types (Link(..))
```
don't work anymore.  Therefore, as long as we're breaking stuff, we might as well just upgrade existing types and functions to be polymorphic and having a cleaner design.  Ironically this may end up unbreaking `Link(..)`.

**Comment by myfreeweb** [comment]
yeah upgrade everything I guess

**Comment by sjshuck** [comment]
Fixed by #13.
