### ISSUE TITLE
Allow attoparsec-0.14

### ISSUE THREAD

**Issue by phadej** [myfreeweb/http-link-header#16]
https://hackage.haskell.org/package/http-link-header-1.2.0 has `attoparsec <0.14` upper bound.

**Comment by sjshuck** [comment]
The PR won't actually fix this, it'll be fixed by running `stack sdist` and uploading the tarball without PVP bounds, which has become my usual practice.  attn @unrelentingtech

**Comment by valpackett** [comment]
How did the pvp bounds end up on there anyway? Did stack auto-generate them when uploading or did hackage trustees edit them in? (I don't see any revision links on the hackage page, but I don't even remember where exactly they're supposed to appear)

**Comment by sjshuck** [comment]
It was probably from when I was running `stack sdist --pvp-bounds` but I don't know for sure.

http-link-header-1.2.1 uploaded.  Confirmed no PVP bounds in Cabal file.  Thanks y'all.
