### ISSUE TITLE
Add parseLinkHeaderBS

### ISSUE THREAD

**Issue by phadej** [myfreeweb/http-link-header#2]
i.e. `parseLinkHeaderBS :: ByteString -> Maybe [Link]`, the [`Header`](https://hackage.haskell.org/package/http-types-0.8.6/docs/Network-HTTP-Types-Header.html#t:Header) type has `ByteString` as a value, converting to `Text` in between feels as unnecessary step.

**Comment by myfreeweb** [comment]
I think `Text` is the recommended way to parse Unicode strings? Also the `Parser ByteString` in attoparsec is less convenient, it lacks `char` (needs `Word8` stuff) and `skipSpace`.

If you mean just adding a function that is the composition of conversion and parsing... I can do that :-)

**Comment by phadej** [comment]
Headers aren't Unicode strings, [In short: Only ASCII is guaranteed to work.](http://stackoverflow.com/questions/4400678/http-header-should-use-what-character-encoding). It's good that `Link` has `Text`.

Yet for now current `parseLinkHeaderBS` is enough for me, thanks!
